/**
 * A QR Code encoder and a clean-matrix decoder, written by hand so the app
 * needs no QR dependency (draft 01, `docs/issue-drafts/01-claim-code-as-qr.md`).
 *
 * Scope: the payload is the organizer's claim code — 64 ASCII hexadecimal
 * characters — so only **byte mode** is implemented, at all four error
 * correction levels. Versions 1..40 are supported (the smallest that fits is
 * chosen), which is every size the standard defines. Numeric, alphanumeric,
 * kanji and ECI segments are deliberately not implemented: nothing in this app
 * encodes them, and a v0 that does one thing correctly beats one that does
 * four things approximately.
 *
 * The decoder here reads a **clean** matrix — no error correction, no camera
 * image, no binarisation. It exists so the round-trip test can prove the
 * encoder is a pure, invertible function (draft 01's acceptance criterion),
 * and it is a starting point for the camera work in draft 02, not a camera
 * decoder.
 *
 * Everything is integer-only and dependency-free, following `badgeArt.ts` and
 * `badgeCsv.ts`: the output is a pure function of the payload and the level, so
 * two machines produce the same matrix, and no network request is involved.
 *
 * Reference for the tables and the bit-level rules: ISO/IEC 18004, as
 * implemented by two independent, MIT-licensed libraries (Nayuki's
 * `QR-Code-generator` and Kazuhiko Arase's `qrcode-generator`), which agree on
 * every value used here. The known-answer test in `qr.test.ts` pins the output
 * against matrices generated by the second of those while the first was read
 * as the specification's cross-check.
 */

export type ErrorCorrectionLevel = 'L' | 'M' | 'Q' | 'H';

/** The standard's required margin of light modules around the symbol. */
export const QR_QUIET_ZONE = 4;

export interface QrMatrix {
  /** Modules per side: `version * 4 + 17`. */
  readonly size: number;
  /** `modules[row][col]`; `true` is a dark module. No quiet zone is included. */
  readonly modules: readonly (readonly boolean[])[];
}

export interface QrOptions {
  /** Force mask pattern 0..7; by default the lowest-penalty mask is chosen. */
  readonly mask?: number;
  /** Force version 1..40; by default the smallest version that fits is used. */
  readonly version?: number;
}

/** Byte mode's mode indicator, `0100` (ISO/IEC 18004 Table 2). */
const MODE_BYTE = 0x4;

/** Table index for each level: L, M, Q, H, as the tables below are ordered. */
const ECC_ORDINAL: Record<ErrorCorrectionLevel, number> = { L: 0, M: 1, Q: 2, H: 3 };

/** The two format bits each level carries (NOT the same as the ordinal). */
const ECC_FORMAT_BITS: Record<ErrorCorrectionLevel, number> = { L: 1, M: 0, Q: 3, H: 2 };

/** Reverse of `ECC_FORMAT_BITS`, indexed by the 2-bit value. */
const ECC_FROM_FORMAT_BITS: readonly ErrorCorrectionLevel[] = ['M', 'L', 'H', 'Q'];

/**
 * Error-correction codewords per block, by level ordinal and version; index 0
 * of each row is unused (there is no version 0).
 */
const ECC_CODEWORDS_PER_BLOCK: readonly (readonly number[])[] = [
  // L
  [-1, 7, 10, 15, 20, 26, 18, 20, 24, 30, 18, 20, 24, 26, 30, 22, 24, 28, 30, 28, 28, 28, 28, 30, 30, 26, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
  // M
  [-1, 10, 16, 26, 18, 24, 16, 18, 22, 22, 26, 30, 22, 22, 24, 24, 28, 28, 26, 26, 26, 26, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28],
  // Q
  [-1, 13, 22, 18, 26, 18, 24, 18, 22, 20, 24, 28, 26, 24, 20, 30, 24, 28, 28, 26, 30, 28, 30, 30, 30, 30, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
  // H
  [-1, 17, 28, 22, 16, 22, 28, 26, 26, 24, 28, 24, 28, 22, 24, 24, 30, 28, 28, 26, 28, 30, 24, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
];

/**
 * Error-correction blocks per symbol, by level ordinal and version; index 0 of
 * each row is unused.
 */
const NUM_ERROR_CORRECTION_BLOCKS: readonly (readonly number[])[] = [
  // L
  [-1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 4, 4, 4, 4, 4, 6, 6, 6, 6, 7, 8, 8, 9, 9, 10, 12, 12, 12, 13, 14, 15, 16, 17, 18, 19, 19, 20, 21, 22, 24, 25],
  // M
  [-1, 1, 1, 1, 2, 2, 4, 4, 4, 5, 5, 5, 8, 9, 9, 10, 10, 11, 13, 14, 16, 17, 17, 18, 20, 21, 23, 25, 26, 28, 29, 31, 33, 35, 37, 38, 40, 43, 45, 47, 49],
  // Q
  [-1, 1, 1, 2, 2, 4, 4, 6, 6, 8, 8, 8, 10, 12, 16, 12, 17, 16, 18, 21, 20, 23, 23, 25, 27, 29, 34, 34, 35, 38, 40, 43, 45, 48, 51, 53, 56, 59, 62, 65, 68],
  // H
  [-1, 1, 1, 2, 4, 4, 4, 5, 6, 8, 8, 11, 11, 16, 16, 18, 16, 19, 21, 25, 25, 25, 34, 30, 32, 35, 37, 40, 42, 45, 48, 51, 54, 57, 60, 63, 66, 70, 74, 77, 81],
];

const MIN_VERSION = 1;
const MAX_VERSION = 40;

function assertVersion(version: number): void {
  if (!Number.isInteger(version) || version < MIN_VERSION || version > MAX_VERSION) {
    throw new RangeError(`QR version must be an integer 1..40, got ${version}`);
  }
}

function getBit(value: number, index: number): boolean {
  return ((value >>> index) & 1) !== 0;
}

/** The number of character-count bits byte mode uses at this version. */
function byteCharCountBits(version: number): number {
  // 8 bits for versions 1..9, 16 for 10..40 (ISO/IEC 18004 Table 3).
  return version < 10 ? 8 : 16;
}

/** Data + error-correction codewords a symbol holds: `raw / 8`. */
function numRawCodewords(version: number): number {
  // Every module is data except the function patterns: finders and their
  // separators, timing, alignment, and (from version 7) the version blocks.
  let result = (16 * version + 128) * version + 64;
  if (version >= 2) {
    const numAlign = Math.floor(version / 7) + 2;
    result -= (25 * numAlign - 10) * numAlign - 55;
    if (version >= 7) result -= 36;
  }
  return Math.floor(result / 8);
}

/** The number of data codewords (before error correction) in a symbol. */
function numDataCodewords(version: number, ordinal: number): number {
  return (
    numRawCodewords(version) -
    ECC_CODEWORDS_PER_BLOCK[ordinal][version] * NUM_ERROR_CORRECTION_BLOCKS[ordinal][version]
  );
}

/** Alignment-pattern centres along one axis, ascending. Empty for version 1. */
function alignmentPatternPositions(version: number): number[] {
  if (version === 1) return [];
  const numAlign = Math.floor(version / 7) + 2;
  const size = version * 4 + 17;
  const step =
    Math.floor((version * 8 + numAlign * 3 + 5) / (numAlign * 4 - 4)) * 2;
  const result: number[] = new Array<number>(numAlign).fill(6);
  // Filled from the far corner inwards, so any rounding remainder lands in the
  // gap nearest the finder pattern (which is how version 32's wider gap arises).
  for (let index = numAlign - 1, pos = size - 7; index >= 1; index -= 1, pos -= step) {
    result[index] = pos;
  }
  return result;
}

/** 15-bit format information for a level and mask, with its BCH and XOR mask. */
function formatInfoBits(level: ErrorCorrectionLevel, mask: number): number {
  const data = (ECC_FORMAT_BITS[level] << 3) | mask;
  let remainder = data;
  for (let index = 0; index < 10; index += 1) {
    remainder = (remainder << 1) ^ ((remainder >>> 9) * 0x537);
  }
  return ((data << 10) | remainder) ^ 0x5412;
}

/** 18-bit version information (versions 7..40) with its BCH. */
function versionInfoBits(version: number): number {
  let remainder = version;
  for (let index = 0; index < 12; index += 1) {
    remainder = (remainder << 1) ^ ((remainder >>> 11) * 0x1f25);
  }
  return (version << 12) | remainder;
}

/** One mask pattern's predicate: `true` means invert the module at (x, y). */
function maskInverts(mask: number, x: number, y: number): boolean {
  switch (mask) {
    case 0:
      return (x + y) % 2 === 0;
    case 1:
      return y % 2 === 0;
    case 2:
      return x % 3 === 0;
    case 3:
      return (x + y) % 3 === 0;
    case 4:
      return (Math.floor(x / 3) + Math.floor(y / 2)) % 2 === 0;
    case 5:
      return ((x * y) % 2) + ((x * y) % 3) === 0;
    case 6:
      return (((x * y) % 2) + ((x * y) % 3)) % 2 === 0;
    case 7:
      return (((x * y) % 3) + ((x + y) % 2)) % 2 === 0;
    default:
      throw new RangeError(`QR mask must be 0..7, got ${mask}`);
  }
}

/** A square module grid that knows which modules are function patterns. */
interface Grid {
  readonly size: number;
  readonly modules: boolean[][];
  readonly isFunction: boolean[][];
}

function emptyGrid(version: number): Grid {
  const size = version * 4 + 17;
  return {
    size,
    modules: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
    isFunction: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
  };
}

/** Sets a module and marks it as a function pattern. `x` is the column. */
function setFunction(grid: Grid, x: number, y: number, dark: boolean): void {
  grid.modules[y][x] = dark;
  grid.isFunction[y][x] = true;
}

function drawFinder(grid: Grid, centerX: number, centerY: number): void {
  for (let dy = -4; dy <= 4; dy += 1) {
    for (let dx = -4; dx <= 4; dx += 1) {
      const x = centerX + dx;
      const y = centerY + dy;
      if (x < 0 || x >= grid.size || y < 0 || y >= grid.size) continue;
      const distance = Math.max(Math.abs(dx), Math.abs(dy));
      setFunction(grid, x, y, distance !== 2 && distance !== 4);
    }
  }
}

function drawAlignment(grid: Grid, centerX: number, centerY: number): void {
  for (let dy = -2; dy <= 2; dy += 1) {
    for (let dx = -2; dx <= 2; dx += 1) {
      setFunction(grid, centerX + dx, centerY + dy, Math.max(Math.abs(dx), Math.abs(dy)) !== 1);
    }
  }
}

/** Draws the format information for one mask in both of its two copies. */
function drawFormatBits(grid: Grid, level: ErrorCorrectionLevel, mask: number): void {
  const bits = formatInfoBits(level, mask);
  const { size } = grid;

  // First copy, around the top-left finder.
  for (let i = 0; i <= 5; i += 1) setFunction(grid, 8, i, getBit(bits, i));
  setFunction(grid, 8, 7, getBit(bits, 6));
  setFunction(grid, 8, 8, getBit(bits, 7));
  setFunction(grid, 7, 8, getBit(bits, 8));
  for (let i = 9; i < 15; i += 1) setFunction(grid, 14 - i, 8, getBit(bits, i));

  // Second copy, split between the other two finders.
  for (let i = 0; i < 8; i += 1) setFunction(grid, size - 1 - i, 8, getBit(bits, i));
  for (let i = 8; i < 15; i += 1) setFunction(grid, 8, size - 15 + i, getBit(bits, i));
  // The module above the bottom-left finder's separator is always dark.
  setFunction(grid, 8, size - 8, true);
}

function drawVersionBits(grid: Grid, version: number): void {
  if (version < 7) return;
  const bits = versionInfoBits(version);
  for (let i = 0; i < 18; i += 1) {
    const bit = getBit(bits, i);
    const a = grid.size - 11 + (i % 3);
    const b = Math.floor(i / 3);
    setFunction(grid, a, b, bit);
    setFunction(grid, b, a, bit);
  }
}

/**
 * Draws every function pattern for a version, recording them so the data
 * placement can skip them. Format bits are drawn for mask 0 here; the encoder
 * redraws them once the mask is chosen, and the decoder reads them instead.
 */
function drawFunctionPatterns(version: number, level: ErrorCorrectionLevel): Grid {
  const grid = emptyGrid(version);
  const { size } = grid;

  for (let i = 0; i < size; i += 1) {
    setFunction(grid, 6, i, i % 2 === 0);
    setFunction(grid, i, 6, i % 2 === 0);
  }

  drawFinder(grid, 3, 3);
  drawFinder(grid, size - 4, 3);
  drawFinder(grid, 3, size - 4);

  const positions = alignmentPatternPositions(version);
  const last = positions.length - 1;
  for (let i = 0; i < positions.length; i += 1) {
    for (let j = 0; j < positions.length; j += 1) {
      const corner =
        (i === 0 && j === 0) || (i === 0 && j === last) || (i === last && j === 0);
      if (!corner) drawAlignment(grid, positions[i], positions[j]);
    }
  }

  drawFormatBits(grid, level, 0);
  drawVersionBits(grid, version);
  return grid;
}

/** Places the codeword bits in the standard two-module zigzag. */
function drawCodewords(grid: Grid, codewords: readonly number[]): void {
  const { size } = grid;
  let bitIndex = 0;
  const totalBits = codewords.length * 8;

  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5; // The vertical timing column is skipped.
    for (let vert = 0; vert < size; vert += 1) {
      for (let j = 0; j < 2; j += 1) {
        const x = right - j;
        const upward = ((right + 1) & 2) === 0;
        const y = upward ? size - 1 - vert : vert;
        if (!grid.isFunction[y][x] && bitIndex < totalBits) {
          grid.modules[y][x] = getBit(codewords[bitIndex >>> 3], 7 - (bitIndex & 7));
          bitIndex += 1;
        }
      }
    }
  }
}

/** Applies one mask pattern to every non-function module. */
function applyMask(grid: Grid, mask: number): void {
  const { size } = grid;
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      if (!grid.isFunction[y][x] && maskInverts(mask, x, y)) {
        grid.modules[y][x] = !grid.modules[y][x];
      }
    }
  }
}

/** The four ISO/IEC 18004 penalty rules N1..N4 (weights 3, 3, 40, 10). */
function penaltyScore(grid: Grid): number {
  const { size, modules } = grid;
  let score = 0;

  // N1: runs of five or more same-coloured modules, in rows then columns.
  const runPenalty = (runLength: number): number =>
    runLength >= 5 ? 3 + (runLength - 5) : 0;
  for (let y = 0; y < size; y += 1) {
    let runColor = modules[y][0];
    let runLength = 1;
    for (let x = 1; x < size; x += 1) {
      if (modules[y][x] === runColor) {
        runLength += 1;
      } else {
        score += runPenalty(runLength);
        runColor = modules[y][x];
        runLength = 1;
      }
    }
    score += runPenalty(runLength);
  }
  for (let x = 0; x < size; x += 1) {
    let runColor = modules[0][x];
    let runLength = 1;
    for (let y = 1; y < size; y += 1) {
      if (modules[y][x] === runColor) {
        runLength += 1;
      } else {
        score += runPenalty(runLength);
        runColor = modules[y][x];
        runLength = 1;
      }
    }
    score += runPenalty(runLength);
  }

  // N2: every 2x2 block of one colour.
  for (let y = 0; y < size - 1; y += 1) {
    for (let x = 0; x < size - 1; x += 1) {
      const color = modules[y][x];
      if (
        color === modules[y][x + 1] &&
        color === modules[y + 1][x] &&
        color === modules[y + 1][x + 1]
      ) {
        score += 3;
      }
    }
  }

  // N3: the finder-like 1:1:3:1:1 pattern with four light modules on a side.
  const PATTERN_A = '10111010000';
  const PATTERN_B = '00001011101';
  const lineHasPattern = (read: (index: number) => boolean): void => {
    for (let start = 0; start + 11 <= size; start += 1) {
      let line = '';
      for (let offset = 0; offset < 11; offset += 1) {
        line += read(start + offset) ? '1' : '0';
      }
      if (line === PATTERN_A || line === PATTERN_B) score += 40;
    }
  };
  for (let y = 0; y < size; y += 1) lineHasPattern((index) => modules[y][index]);
  for (let x = 0; x < size; x += 1) lineHasPattern((index) => modules[index][x]);

  // N4: how far the dark proportion sits from 50%, in 5% steps.
  let dark = 0;
  for (const row of modules) {
    for (const module of row) if (module) dark += 1;
  }
  const total = size * size;
  score += 10 * Math.floor(Math.abs(dark * 20 - total * 10) / total);

  return score;
}

/** Galois-field double-and-add multiply in GF(2^8) with primitive 0x11D. */
function reedSolomonMultiply(x: number, y: number): number {
  let z = 0;
  for (let i = 7; i >= 0; i -= 1) {
    z = (z << 1) ^ ((z >>> 7) * 0x11d);
    z ^= ((y >>> i) & 1) * x;
  }
  return z & 0xff;
}

/** The generator polynomial for `degree` error-correction codewords. */
function reedSolomonDivisor(degree: number): number[] {
  const result = new Array<number>(degree).fill(0);
  result[degree - 1] = 1;
  let root = 1;
  for (let i = 0; i < degree; i += 1) {
    for (let j = 0; j < result.length; j += 1) {
      result[j] = reedSolomonMultiply(result[j], root);
      if (j + 1 < result.length) result[j] ^= result[j + 1];
    }
    root = reedSolomonMultiply(root, 0x02);
  }
  return result;
}

/** The remainder of `data` divided by `divisor`: the codewords' check bytes. */
function reedSolomonRemainder(data: readonly number[], divisor: readonly number[]): number[] {
  const result = new Array<number>(divisor.length).fill(0);
  for (const byte of data) {
    const factor = byte ^ result[0];
    for (let i = 0; i < result.length - 1; i += 1) result[i] = result[i + 1];
    result[result.length - 1] = 0;
    for (let i = 0; i < result.length; i += 1) {
      result[i] ^= reedSolomonMultiply(divisor[i], factor);
    }
  }
  return result;
}

/** The data codewords for byte mode, with the terminator and pad bytes. */
function buildDataCodewords(bytes: readonly number[], version: number, ordinal: number): number[] {
  const capacityBits = numDataCodewords(version, ordinal) * 8;
  const bits: boolean[] = [];
  const append = (value: number, length: number): void => {
    for (let i = length - 1; i >= 0; i -= 1) bits.push(getBit(value, i));
  };

  append(MODE_BYTE, 4);
  append(bytes.length, byteCharCountBits(version));
  for (const byte of bytes) append(byte, 8);

  // Terminator, up to four zero bits, then pad to the next byte boundary.
  const terminator = Math.min(4, capacityBits - bits.length);
  if (terminator < 0) throw new RangeError('QR payload does not fit the chosen version');
  append(0, terminator);
  append(0, (8 - (bits.length % 8)) % 8);

  // Alternate pad codewords 0xEC / 0x11 until the symbol is full.
  let pad = 0xec;
  while (bits.length < capacityBits) {
    append(pad, 8);
    pad ^= 0xec ^ 0x11;
  }

  const codewords: number[] = [];
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j += 1) byte = (byte << 1) | (bits[i + j] ? 1 : 0);
    codewords.push(byte);
  }
  return codewords;
}

/**
 * Splits the data codewords into blocks, appends each block's error-correction
 * codewords, and interleaves them in the standard order.
 */
function addEccAndInterleave(
  dataCodewords: readonly number[],
  version: number,
  ordinal: number,
): number[] {
  const numBlocks = NUM_ERROR_CORRECTION_BLOCKS[ordinal][version];
  const blockEccLen = ECC_CODEWORDS_PER_BLOCK[ordinal][version];
  const rawCodewords = numRawCodewords(version);
  const numShortBlocks = numBlocks - (rawCodewords % numBlocks);
  const shortBlockLen = Math.floor(rawCodewords / numBlocks);

  const divisor = reedSolomonDivisor(blockEccLen);
  const blocks: number[][] = [];
  for (let i = 0, k = 0; i < numBlocks; i += 1) {
    const dataLen = shortBlockLen - blockEccLen + (i < numShortBlocks ? 0 : 1);
    const dat = dataCodewords.slice(k, k + dataLen);
    k += dataLen;
    // Every block has `shortBlockLen + 1` codeword slots: the data, one spare
    // (left zero for a short block) and then the error-correction codewords in
    // the final `blockEccLen` slots. Interleaving skips the spare slot.
    const block = new Array<number>(shortBlockLen + 1).fill(0);
    for (let j = 0; j < dat.length; j += 1) block[j] = dat[j];
    const ecc = reedSolomonRemainder(dat, divisor);
    for (let j = 0; j < ecc.length; j += 1) block[block.length - blockEccLen + j] = ecc[j];
    blocks.push(block);
  }

  const result: number[] = [];
  for (let i = 0; i < blocks[0].length; i += 1) {
    for (let j = 0; j < blocks.length; j += 1) {
      if (i !== shortBlockLen - blockEccLen || j >= numShortBlocks) {
        result.push(blocks[j][i]);
      }
    }
  }
  return result;
}

/** The smallest version whose data capacity holds this many bytes. */
function pickVersion(bytes: number, ordinal: number): number {
  for (let version = MIN_VERSION; version <= MAX_VERSION; version += 1) {
    const neededBits = 4 + byteCharCountBits(version) + bytes * 8;
    if (neededBits <= numDataCodewords(version, ordinal) * 8) return version;
  }
  throw new RangeError(`QR payload of ${bytes} bytes is too large for version 40`);
}

/**
 * Encodes `text` (UTF-8 bytes for non-ASCII) as a QR symbol. The returned
 * matrix excludes the quiet zone; render it with at least `QR_QUIET_ZONE`
 * modules of light margin on every side.
 */
export function qrEncode(
  text: string,
  level: ErrorCorrectionLevel,
  options: QrOptions = {},
): QrMatrix {
  const bytes = Array.from(new TextEncoder().encode(text));
  const ordinal = ECC_ORDINAL[level];
  const version = options.version ?? pickVersion(bytes.length, ordinal);
  assertVersion(version);
  if (bytes.length > 0xffff) {
    throw new RangeError('QR byte-mode payload exceeds the 16-bit length field');
  }

  const dataCodewords = buildDataCodewords(bytes, version, ordinal);
  const codewords = addEccAndInterleave(dataCodewords, version, ordinal);

  let bestPenalty = Number.POSITIVE_INFINITY;
  const masks = options.mask === undefined ? [0, 1, 2, 3, 4, 5, 6, 7] : [options.mask];
  let bestGrid: Grid | null = null;

  for (const mask of masks) {
    if (!Number.isInteger(mask) || mask < 0 || mask > 7) {
      throw new RangeError(`QR mask must be an integer 0..7, got ${mask}`);
    }
    const grid = drawFunctionPatterns(version, level);
    drawCodewords(grid, codewords);
    applyMask(grid, mask);
    drawFormatBits(grid, level, mask);
    const penalty = penaltyScore(grid);
    if (penalty < bestPenalty) {
      bestPenalty = penalty;
      bestGrid = grid;
    }
  }

  if (bestGrid === null) throw new Error('no mask was evaluated');
  // Copy the rows out so the returned matrix cannot be mutated by a caller.
  return { size: bestGrid.size, modules: bestGrid.modules.map((row) => row.slice()) };
}

/** Reads 15 format-info bits from the first copy and returns the 5 data bits. */
function readFormatBits(qr: QrMatrix): number {
  const { modules } = qr;
  const read = (x: number, y: number, index: number): number =>
    modules[y][x] ? 1 << index : 0;
  let bits = 0;
  for (let i = 0; i <= 5; i += 1) bits |= read(8, i, i);
  bits |= read(8, 7, 6);
  bits |= read(8, 8, 7);
  bits |= read(7, 8, 8);
  for (let i = 9; i < 15; i += 1) bits |= read(14 - i, 8, i);
  return (bits ^ 0x5412) >>> 10;
}

/**
 * Decodes a clean, error-free module matrix back to its text. Only byte-mode
 * symbols are handled; anything else throws. This is the round-trip partner of
 * `qrEncode` (and a base for draft 02), not an image decoder: it does no error
 * correction and assumes every module is exactly as encoded.
 */
export function qrDecode(qr: QrMatrix): string {
  const { size } = qr;
  const version = Math.round((size - 17) / 4);
  assertVersion(version);
  if (version * 4 + 17 !== size) {
    throw new RangeError(`QR size ${size} is not a valid symbol size`);
  }

  const formatData = readFormatBits(qr);
  const level = ECC_FROM_FORMAT_BITS[formatData >>> 3];
  const mask = formatData & 0x07;
  const ordinal = ECC_ORDINAL[level];

  // Rebuild the function-pattern layout and unmask the data modules.
  const grid = drawFunctionPatterns(version, level);
  const modules = qr.modules.map((row) => row.slice());
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      if (!grid.isFunction[y][x] && maskInverts(mask, x, y)) modules[y][x] = !modules[y][x];
    }
  }

  // Read the codewords back out of the zigzag.
  const rawCodewords = numRawCodewords(version);
  const codewords = new Array<number>(rawCodewords).fill(0);
  let bitIndex = 0;
  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5;
    for (let vert = 0; vert < size; vert += 1) {
      for (let j = 0; j < 2; j += 1) {
        const x = right - j;
        const upward = ((right + 1) & 2) === 0;
        const y = upward ? size - 1 - vert : vert;
        if (!grid.isFunction[y][x] && bitIndex < rawCodewords * 8) {
          if (modules[y][x]) codewords[bitIndex >>> 3] |= 1 << (7 - (bitIndex & 7));
          bitIndex += 1;
        }
      }
    }
  }

  // Undo the block interleaving: gather each block, then drop its ECC.
  const numBlocks = NUM_ERROR_CORRECTION_BLOCKS[ordinal][version];
  const blockEccLen = ECC_CODEWORDS_PER_BLOCK[ordinal][version];
  const numShortBlocks = numBlocks - (rawCodewords % numBlocks);
  const shortBlockLen = Math.floor(rawCodewords / numBlocks);
  const blocks: number[][] = Array.from({ length: numBlocks }, () =>
    new Array<number>(shortBlockLen + 1).fill(0),
  );
  for (let i = 0, k = 0; i < shortBlockLen + 1; i += 1) {
    for (let j = 0; j < numBlocks; j += 1) {
      if (i !== shortBlockLen - blockEccLen || j >= numShortBlocks) {
        blocks[j][i] = codewords[k];
        k += 1;
      }
    }
  }

  const dataCodewords: number[] = [];
  for (let i = 0; i < numBlocks; i += 1) {
    const dataLen = shortBlockLen - blockEccLen + (i < numShortBlocks ? 0 : 1);
    for (let j = 0; j < dataLen; j += 1) dataCodewords.push(blocks[i][j]);
  }

  // Parse the bit stream: a 4-bit mode indicator then the byte-mode segment.
  const dataBits: boolean[] = [];
  for (const codeword of dataCodewords) {
    for (let i = 7; i >= 0; i -= 1) dataBits.push(getBit(codeword, i));
  }
  const readBits = (start: number, length: number): number => {
    let value = 0;
    for (let i = 0; i < length; i += 1) value = (value << 1) | (dataBits[start + i] ? 1 : 0);
    return value;
  };

  const mode = readBits(0, 4);
  if (mode !== MODE_BYTE) {
    throw new Error(`unsupported QR segment mode 0x${mode.toString(16)} (byte mode only)`);
  }
  const lengthBits = byteCharCountBits(version);
  const length = readBits(4, lengthBits);
  const payload = new Uint8Array(length);
  let cursor = 4 + lengthBits;
  for (let i = 0; i < length; i += 1) {
    payload[i] = readBits(cursor, 8);
    cursor += 8;
  }
  return new TextDecoder().decode(payload);
}
