import * as axe from 'axe-core';
import { cleanup, render, type RenderResult } from '@testing-library/react';
import { afterEach } from 'vitest';

import { Keypair, StrKey } from '@stellar/stellar-sdk';
import type { ReactElement } from 'react';

import type { BadgeRecord, EventRecord } from '../lib/badge';
import type { ContractClient, SubmitResult } from '../lib/contract';
import type { WalletController } from '../hooks/useWallet';
import type { AppConfig } from '../lib/network';
import type { PageProps } from '../pages/shared';

// RTL's auto-cleanup registers via the global afterEach, which vitest does not
// enable with globals: false, so run it here for every render test.
afterEach(() => {
  cleanup();
});

/**
 * Renders into happy-dom (act-safe, via RTL) and runs the axe-core
 * accessibility check, rejecting on serious or critical violations.
 */
export async function renderWithA11y(ui: ReactElement): Promise<RenderResult> {
  const result = render(ui);
  const results = await axe.run(result.container, {
    resultTypes: ['violations'],
    // Stylesheets are not loaded in the test DOM, so axe cannot compute real
    // contrast ratios here; contrast is covered by the design tokens, which
    // were measured by hand.
    rules: { 'color-contrast': { enabled: false } },
  });
  const serious = results.violations.filter(
    (v) => v.impact === 'serious' || v.impact === 'critical',
  );
  if (serious.length > 0) {
    throw new Error(
      `axe found ${serious.length} serious/critical violations: ` +
        serious
          .map((v) => `${v.id}: ${v.nodes.map((n) => n.target.join(' ')).join(', ')}`)
          .join('; '),
    );
  }
  return result;
}

/**
 * Renders and returns the queries, skipping the accessibility check — for
 * tests that assert something axe would legitimately flag elsewhere in the
 * fixture, or where the a11y check is covered by another test.
 */
export function renderOnly(ui: ReactElement): RenderResult {
  return render(ui);
}

/**
 * Queries text across the container, including inside hidden (sr-only) nodes.
 * happy-dom keeps clipped content in the DOM and in textContent, so the
 * sr-only additions are assertable here.
 */
export function textOf(container: HTMLElement): string {
  return container.textContent ?? '';
}

/**
 * A fake account address, generated by the real SDK so it passes the same
 * StrKey checksum validation the app applies. Random, never a real account,
 * and never derived from any personal data.
 */
export function fakeAccount(_seed = 0): string {
  return Keypair.random().publicKey();
}

/**
 * A fake contract id, encoded by the real SDK so it passes StrKey validation.
 * The seed fills the 32-byte payload deterministically; it is not a real
 * contract on any network.
 */
export function fakeContractId(seed = 0): string {
  return StrKey.encodeContract(new Uint8Array(32).fill(seed & 0xff));
}

const FAKE_HASH = 'a'.repeat(64);

/** Builds an EventRecord with a far-future deadline (open window) by default. */
export function eventFactory(overrides: Partial<EventRecord> = {}): EventRecord {
  return {
    id: 1n,
    organizer: fakeAccount(1),
    nameHash: new Uint8Array(32).fill(0x11),
    claimRoot: new Uint8Array(32).fill(0x22),
    maxClaims: 100,
    closesAt: 4_102_444_800n, // 2100-01-01, so the window is open in tests.
    claimCount: 0,
    ...overrides,
  };
}

/** Builds a BadgeRecord bound to the default factory event. */
export function badgeFactory(overrides: Partial<BadgeRecord> = {}): BadgeRecord {
  return {
    eventId: 1n,
    attendee: fakeAccount(3),
    organizer: fakeAccount(4),
    issuedAt: 1_790_000_000n,
    ...overrides,
  };
}

/** A connected, testnet wallet double with no real address. */
export function walletFactory(overrides: Partial<WalletController> = {}): WalletController {
  return {
    address: fakeAccount(5),
    connecting: false,
    error: null,
    onTestnet: true,
    prepare: () => {},
    connect: async () => {},
    disconnect: async () => {},
    refreshNetwork: async () => true,
    ...overrides,
  };
}

/** A valid-in-shape AppConfig pointing at localhost — never used on air. */
export function configFactory(overrides: Partial<AppConfig> = {}): AppConfig {
  return {
    network: 'testnet',
    passphrase: 'Test SDF Network ; September 2015',
    rpcUrl: 'http://127.0.0.1:8000',
    contractId: fakeContractId(6),
    explorerBaseUrl: 'https://example.testexplorer.invalid',
    ...overrides,
  };
}

/**
 * A ContractClient double. Reads are answered from the `events` and `badges`
 * lists; writes return a fake hash. No method reaches a network. Read and
 * write failures can be injected one shot at a time so error-mapping paths are
 * exercised the way the real client throws.
 */
export function clientFactory(
  events: EventRecord[] = [],
  badges: BadgeRecord[] = [],
): ContractClient & {
  failNextReadWith: (error: unknown) => void;
  failNextWriteWith: (error: unknown) => void;
  /** Every `create_event` the page prepared, so tests can assert on the root. */
  preparedCreates: Parameters<ContractClient['prepareCreateEvent']>[0][];
  /** Every `claim` the page prepared, so tests can assert on the arguments. */
  preparedClaims: Parameters<ContractClient['prepareClaim']>[0][];
} {
  const eventById = new Map(events.map((event) => [event.id, event]));
  const preparedCreates: Parameters<ContractClient['prepareCreateEvent']>[0][] = [];
  const preparedClaims: Parameters<ContractClient['prepareClaim']>[0][] = [];
  let readFailure: unknown = null;
  let writeFailure: unknown = null;

  function throwRead(): void {
    if (readFailure !== null) {
      const error = readFailure;
      readFailure = null;
      throw error;
    }
  }

  const submit = async (): Promise<SubmitResult> => {
    if (writeFailure !== null) {
      const error = writeFailure;
      writeFailure = null;
      throw error;
    }
    return { hash: FAKE_HASH };
  };

  return {
    async getEvent(_source, eventId) {
      throwRead();
      const event = eventById.get(eventId);
      if (event === undefined) {
        throw new Error('HostError: Error(Contract, #1)');
      }
      return event;
    },
    async hasBadge(_source, eventId, attendee) {
      throwRead();
      return badges.some((badge) => badge.eventId === eventId && badge.attendee === attendee);
    },
    async badgesOf(_source, eventId, attendee) {
      throwRead();
      return badges.filter((badge) => badge.eventId === eventId && badge.attendee === attendee);
    },
    async prepareCreateEvent(input) {
      throwRead();
      preparedCreates.push(input);
      return { xdr: 'fake-xdr' };
    },
    async prepareClaim(input) {
      throwRead();
      preparedClaims.push(input);
      return { xdr: 'fake-xdr' };
    },
    async prepareAward() {
      throwRead();
      return { xdr: 'fake-xdr' };
    },
    async prepareRevoke() {
      throwRead();
      return { xdr: 'fake-xdr' };
    },
    submit,
    preparedCreates,
    preparedClaims,
    failNextReadWith(error: unknown) {
      readFailure = error;
    },
    failNextWriteWith(error: unknown) {
      writeFailure = error;
    },
  };
}

/** PageProps assembled from the doubles, ready to spread into a page. */
export function pagePropsFactory(
  options: {
    client?: ContractClient;
    config?: AppConfig;
    wallet?: WalletController;
  } = {},
): PageProps {
  return {
    client: options.client ?? clientFactory([]),
    config: options.config ?? configFactory(),
    wallet: options.wallet ?? walletFactory(),
  };
}
